fix: throw error instead of logging for duplicate user creation
FreeCodeCamp/open-api pull request #150
Opened 2018-05-13 06:41 UTC by sivakar12

ISSUES CLOSED: #148

2018-05-13 08:07 UTC, sivakar12 commented
It looks like many tests are creating the same user again and again. Because we throw an error here those tests are failing. Should we remove the created user after each test ends? Or is there a better way?

2018-05-13 23:28 UTC, ojongerius commented
I think we should create different users, unless we explicitly are testing for duplicates.

2018-05-14 03:11 UTC, ojongerius requested changes

2018-05-14 03:11 UTC, ojongerius commented on src/dataLayer/mongo/user.js
> +    throw new Error('The accountLinkId is already in use');
Could we please change this to "Account already in use"? -I'd like to keep accountLinkId internal.

2018-05-15 22:53 UTC, ojongerius approved these changes
LGTM 🎉

2018-05-15 22:54 UTC, ojongerius commented
@sivakar12 could you please rebase against staging so we can merge this in?

2018-05-16 04:30 UTC, sivakar12 commented
The rebasing messed up the tests. I had to write them again. I couldn't remember how it looked earlier. I had to add another mock user to make things easier.
You may have to review the tests again

2018-05-16 04:37 UTC, ojongerius commented
That's interesting `node_modules/graphql-tools/dist/schemaGenerator.js` now logs 

```
    { Error: You must provide a valid email
        at createUser (/home/travis/build/freeCodeCamp/open-api/src/dataLayer/mongo/user.js:39:11)
        at Object.<anonymous> (/home/travis/build/freeCodeCamp/open-api/node_modules/graphql-tools/src/schemaGenerator.ts:683:22)
        at class_1.<anonymous> (/home/travis/build/freeCodeCamp/open-api/node_modules/graphql-tools/src/schemaGenerator.ts:781:42)
        at step (/home/travis/build/freeCodeCamp/open-api/node_modules/graphql-tools/dist/schemaGenerator.js:51:23)
        at Object.next (/home/travis/build/freeCodeCamp/open-api/node_modules/graphql-tools/dist/schemaGenerator.js:32:53)
        at /home/travis/build/freeCodeCamp/open-api/node_modules/graphql-tools/dist/schemaGenerator.js:26:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/travis/build/freeCodeCamp/open-api/node_modules/graphql-tools/dist/schemaGenerator.js:22:12)
        at /home/travis/build/freeCodeCamp/open-api/node_modules/graphql-tools/src/schemaGenerator.ts:781:13
        at isAuthenticatedOnQuery (/home/travis/build/freeCodeCamp/open-api/src/graphql/resolvers/directives.js:24:32)
        at field.resolve (/home/travis/build/freeCodeCamp/open-api/node_modules/graphql-tools/src/schemaGenerator.ts:780:18)
        at resolveFieldValueOrError (/home/travis/build/freeCodeCamp/open-api/node_modules/graphql/execution/execute.js:531:18)
        at resolveField (/home/travis/build/freeCodeCamp/open-api/node_modules/graphql/execution/execute.js:495:16)
        at /home/travis/build/freeCodeCamp/open-api/node_modules/graphql/execution/execute.js:339:18
        at /home/travis/build/freeCodeCamp/open-api/node_modules/graphql/jsutils/promiseReduce.js:25:10
        at Array.reduce (<anonymous>)
      originalMessage: 'You must provide a valid email',
      message: 'Error in resolver Mutation.createUser\nYou must provide a valid email' }
```

Lets keep that out of scope of the issue.

2018-05-16 04:42 UTC, sivakar12 commented
Wasn't this always the case? It does not show when --silent flag is given in our local environment. But in the CI there is no silent so you can see it.
I don't this has anything to do with this issue

2018-05-16 04:52 UTC, ojongerius commented
Thanks for all that work @sivakar12 !

2018-05-16 04:52 UTC, merged

2018-05-16 21:34 UTC, ojongerius commented
@sivakar12 re: "Wasn't this always the case", you are absolutely right.