fix(tools): include email when generating JWT token
FreeCodeCamp/open-api pull request #154
Opened 2018-05-14 00:59 UTC by user512

ISSUES CLOSED: #152

2018-05-14 02:38 UTC, ojongerius requested changes

2018-05-14 02:38 UTC, ojongerius commented on test/integration/__snapshots__/userFlow.test.js.snap
> +  [GraphQLError: You must provide a vaild email],
"vaild" should be valid, if you fix the snapshot you'll fix the typo on the code too.

2018-05-14 02:38 UTC, ojongerius commented on test/integration/__snapshots__/userFlow.test.js.snap
> +exports[`createUser should raise an error without email in header: no email 1`] = `
token, not header.

2018-05-14 02:38 UTC, ojongerius commented on test/integration/__snapshots__/userFlow.test.js.snap
> +exports[`createUser should raise an error without email in header: null 1`] = `null`;
token instead of header.

2018-05-14 02:38 UTC, ojongerius commented on test/integration/userFlow.test.js
> +const noEmailContextMarv = global.mockedContextWithNoEmailTokenForMarv;
could we please use contextNoEmail instead? I think using names in constants is fine if we test a scenario where we validate behaviour with multiple users but this only tests the lack of email in the context.

2018-05-14 02:38 UTC, ojongerius commented on test/integration/userFlow.test.js
> +  it('should raise an error without email in header', done => {
context instead of header.

2018-05-14 02:38 UTC, ojongerius commented on test/utils/test-environment.js
> +    const headersWithNoEmailTokenForMarv = {
remove Marv -see comments about not using a name unless it has a function / communicates an intention.

2018-05-14 14:17 UTC, user512 commented
Thanks for the feedback, will amend the commit today.

2018-05-15 08:30 UTC, ojongerius approved these changes
LGTM 🎉

2018-05-15 08:30 UTC, merged