chore: update tooling
FreeCodeCamp/open-api pull request #31
Opened 2018-04-04 07:24 UTC by raisedadead

2018-04-04 07:29 UTC, raisedadead commented
I have integrated most of the tooling and chore stuff. 

- With this when you do a `npm run commit` the code will be lint-ed and automatically formatted.
- You will be able to have nice standard commit messages.
- We can expand the scopes as need arises.

Bonus, added all of the snyk stuff to CI.

2018-04-04 07:30 UTC, raisedadead commented
Yup, again the snyk error is expected coming in from a devDependency.

2018-04-04 07:32 UTC, raisedadead commented
Note: I have knowingly NOT used our own adapter (cz-freecodecamp) here, its quite obsolete. And needs refactoring in its own code to be generic.

Thats's fine which we can ignore for this project and get back to later.

2018-04-05 03:47 UTC, ojongerius requested changes

2018-04-05 03:47 UTC, ojongerius commented on commitizen.config.js
> +    name: "revert:   Revert to a commit"
Maybe "revert a commit" -as you revert commits, and record new commits for them.

2018-04-08 22:34 UTC, merged